apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: djlwc941c-dotnet-basic
  janus-idp.io/tekton: djlwc941c-dotnet-basic
  backstage.io/kubernetes-id: djlwc941c-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: djlwc941c-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
